---
server:
  port: 8082
spring:
  application:
    name: restaurant
  data:
    mongodb:
      uri: mongodb://localhost:27017/zomato
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
